# Generated by Django 2.2.6 on 2020-03-15 06:05

from django.db import migrations, models
import django.db.models.deletion
import django_matplotlib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cate_Jueg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cate_serv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='servi_juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nom_abre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('pre_servi', models.FloatField()),
                ('categoria_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.cate_serv')),
            ],
        ),
        migrations.CreateModel(
            name='mega_juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('nom_abre', models.CharField(max_length=100, verbose_name='Nombre Abreviado')),
                ('fecha_registro', models.DateField(verbose_name='Fecha Registro')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('descri_abre', models.CharField(max_length=100, verbose_name='Descripcion Abreviada')),
                ('enlacegd', models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive')),
                ('enlacegd2', models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 2')),
                ('enlacegd3', models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 3')),
                ('enlacemg', models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega ')),
                ('enlacemg2', models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega 2')),
                ('enlacemg3', models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega 3')),
                ('enlace_publi', models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Google Drive 1')),
                ('enlace_publi2', models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Google Drive 2')),
                ('enlace_publi3', models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Google Drive 3')),
                ('enlace_publimg', models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Mega 1')),
                ('enlace_publimg2', models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Mega 2')),
                ('enlace_publimg3', models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Mega 3')),
                ('slug', models.SlugField()),
                ('imagen', models.ImageField(upload_to='')),
                ('imagen2', models.ImageField(upload_to='')),
                ('imagen3', models.ImageField(upload_to='')),
                ('categoria_pro', models.ManyToManyField(to='juegos.cate_Jueg', verbose_name='Categoria Producto')),
            ],
        ),
    ]
