# Generated by Django 2.2.6 on 2020-03-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requisitos_completo',
            new_name='requisitos_completos',
        ),
    ]
