# Generated by Django 2.2.6 on 2020-03-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
