# Generated by Django 2.2.6 on 2020-03-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mega_juego',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
