# Generated by Django 2.2.6 on 2020-03-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_cate_serv_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cate_serv',
            old_name='slug',
            new_name='slug2',
        ),
    ]
