# Generated by Django 2.2.6 on 2020-03-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0005_auto_20200315_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate_serv',
            name='slug2',
        ),
        migrations.AddField(
            model_name='cate_jueg',
            name='slug2',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
