# Generated by Django 2.2.6 on 2020-03-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0006_auto_20200315_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisitos_completo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU', models.CharField(max_length=150)),
                ('RAM', models.CharField(max_length=150)),
                ('Targeta_Grafica', models.CharField(max_length=150)),
                ('SO', models.CharField(max_length=50)),
                ('Memoria_disk', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='anio_estreno',
            field=models.DateField(blank=True, max_length=4, null=True, verbose_name='Descripcion Abreviada'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='requisitos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='requisitos_completo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.requisitos_completo', verbose_name='Requisitos Completos'),
        ),
    ]
