# Generated by Django 2.2.6 on 2020-03-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0007_auto_20200318_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mega_juego',
            name='requisitos',
            field=models.CharField(blank=True, choices=[('requisitos-bajos', 'Requisitos Bajos'), ('requisitos-medios', 'Requisitos Medios'), ('requisitos-altos', 'Requisitos Altos')], default=('requisitos-bajos', 'Requisitos Bajos'), max_length=50, null=True, verbose_name='Requisitos'),
        ),
    ]
