# Generated by Django 2.2.6 on 2020-03-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0007_auto_20200316_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mega_juego',
            name='requisitos_completo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juegos.requisitos_completo', verbose_name='Requisitos Completos'),
        ),
    ]
